window.sjs_menus = {
    varMenu: "getVarMenu",
    dateFormatMenu: Menu(
        [
            MenuItem("date and time", "datetime"),
            MenuItem("date only", "date"),
            MenuItem("time only", "time"),
            MenuItem("timestamp", "timestamp"),
        ],
        "datetime",
    ),
    caseTypeMenu: Menu(
        [
            MenuItem("UPPERCASE", "uppercase"),
            MenuItem("lowercase", "lowercase"),
        ],
        "uppercase",
    ),
    userInfoMenu: Menu(
        [
            MenuItem("operating system", "OS"),
            MenuItem("browser", "browser"),
            MenuItem("language", "language"),
            MenuItem("time zone", "timezone"),
            MenuItem("screen width", "screenWidth"),
            MenuItem("screen height", "screenHeight"),
            MenuItem("window width", "windowWidth"),
            MenuItem("window height", "windowHeight"),
            MenuItem("device pixel ratio", "devicePixelRatio"),
        ],
        "OS",
    ),
    boolOpMenu: Menu(
        [
            MenuItem("AND", "and"),
            MenuItem("OR", "or"),
            MenuItem("XOR", "xor"),
            MenuItem("NAND", "nand"),
            MenuItem("NOR", "nor"),
            MenuItem("XNOR", "xnor"),
            MenuItem("Implies", "implies"),
            MenuItem("Not-Implies", "n-implies"),
            MenuItem(">", "greater"),
            MenuItem("<", "less"),
            MenuItem("≥", "greater-equal"),
            MenuItem("≤", "less-equal"),
            MenuItem("=", "equal"),
            MenuItem("===", "exactly-equal"),
            MenuItem("≠", "not-equal"),
            MenuItem("+", "add"),
            MenuItem("-", "subtract"),
            MenuItem("×", "multiply"),
            MenuItem("÷", "divide"),
            MenuItem("%", "modulo"),
            MenuItem("^", "power"),
            MenuItem("* 10^", "scientific"),
            MenuItem("join", "join"),
            MenuItem("contains", "contains"),
            MenuItem("starts with", "startsWith"),
            MenuItem("ends with", "endsWith"),
            MenuItem("repeated", "repeated"),
            MenuItem("pad start with spaces", "padstart"),
            MenuItem("pad end with spaces", "padend"),
            MenuItem("bitwise AND", "bitwise-and"),
            MenuItem("bitwise OR", "bitwise-or"),
            MenuItem("bitwise XOR", "bitwise-xor"),
            MenuItem("bitwise NOT", "bitwise-not"),
            MenuItem("left shift", "left-shift"),
            MenuItem("right shift", "right-shift"),
            MenuItem("zero-fill right shift", "zero-fill-right-shift"),
        ],
        "and",
    ),
    padSideMenu: Menu(
        [MenuItem("left", "left"), MenuItem("right", "right")],
        "left",
    ),
    historyActionMenu: Menu(
        [MenuItem("back", "back"), MenuItem("forward", "forward")],
        "back",
    ),
    httpMethodMenu: Menu(
        [
            MenuItem("GET", "GET"),
            MenuItem("POST", "POST"),
            MenuItem("PUT", "PUT"),
            MenuItem("DELETE", "DELETE"),
        ],
        "GET",
    ),
    timeFormatMenu: Menu(
        [
            MenuItem("ISO", "ISO"),
            MenuItem("local", "local"),
            MenuItem("date", "date"),
            MenuItem("time", "time"),
            MenuItem("unix", "unix"),
        ],
        "ISO",
    ),
    hashAlgorithmMenu: Menu([MenuItem("simple", "simple")], "simple"),
    diceSidesMenu: Menu(
        [
            MenuItem("4", "4"),
            MenuItem("6", "6"),
            MenuItem("8", "8"),
            MenuItem("10", "10"),
            MenuItem("12", "12"),
            MenuItem("20", "20"),
            MenuItem("100", "100"),
        ],
        "6",
    ),
    passwordOptionsMenu: Menu(
        [
            MenuItem("letters", "letters"),
            MenuItem("numbers", "numbers"),
            MenuItem("letters+numbers", "letters+numbers"),
            MenuItem("all", "all"),
        ],
        "letters+numbers",
    ),
    rpsMenu: Menu(
        [
            MenuItem("rock", "rock"),
            MenuItem("paper", "paper"),
            MenuItem("scissors", "scissors"),
        ],
        "rock",
    ),
    variableTypeMenu: Menu(
        [
            MenuItem("Sprite", "target"),
            MenuItem("Global", "global"),
        ],
        "target",
    ),
};